### ISSUE TITLE
About exact macOS version

### ISSUE THREAD

**Issue by JiaHeWG** [elmaleek03/Toshiba-Portege-Z30-B-Hackintosh#1]
I'm considering which macOS version should i choose.Is it suits for ALL macOS BigSur version or even higher?Thanks.

**Comment by elmaleek03** [comment]
hello, i have using this EFI till macOS Ventura. But the performance isnot really well. I recommend you to just stick with Big Sur

**Comment by JiaHeWG** [comment]
Okay,i.got it. Thank you!

**Comment by JiaHeWG** [comment]
Okay,i got it. Thank you!
