### ISSUE TITLE
WLAN couldn't work

### ISSUE THREAD

**Issue by JiaHeWG** [elmaleek03/Toshiba-Portege-Z30-B-Hackintosh#2]
I installed macOS Big Sur 11.6.6.There is a problem that i couldn't use my wlan card.im sure it's intel ac7265 card and the bluetooth works well(couldn't off).need i do something else to boot the ac7265 card?

**Comment by JiaHeWG** [comment]
Update.I solved the wifi problem by replacing Airportltlwm.kext drive file which updated in Aug,2021.but now my bluetooth still couldn't be off now.

**Comment by elmaleek03** [comment]
for fixing Intel WiFi / BT, you can refer to zxystd's kexts and the wiki at https://github.com/OpenIntelWireless/itlwm

**Comment by JiaHeWG** [comment]
Thanks a lot. I fixed the issue and it works well now.
